INSERT INTO TITRE
SELECT * FROM HOTEL.TITRE;

INSERT INTO TYPE
SELECT * FROM HOTEL.TYPE;

INSERT INTO CLIENT 
SELECT * FROM HOTEL.CLIENT;

INSERT INTO EMAIL
SELECT * FROM HOTEL.EMAIL;

INSERT INTO TELEPHONE
SELECT * FROM HOTEL.TELEPHONE;

INSERT INTO ADRESSE
SELECT * FROM HOTEL.ADRESSE;

INSERT INTO MODE_PAIEMENT
SELECT * FROM HOTEL.MODE_PAIEMENT;

INSERT INTO FACTURE
SELECT * FROM HOTEL.FACTURE WHERE EXTRACT(YEAR FROM FAC_DATE) = 2007;

INSERT INTO LIGNE_FACTURE
SELECT * FROM HOTEL.LIGNE_FACTURE WHERE FAC_ID IN (SELECT FAC_ID FROM FACTURE);

INSERT INTO AGENT_ENTRETIEN
SELECT * FROM HOTEL.AGENT_ENTRETIEN;

INSERT INTO CHAMBRE
SELECT CHB_ID, CHB_COMMUNIQUE, AGT_ID, CHB_NUMERO, CHB_ETAGE, CHB_BAIN, CHB_DOUCHE, CHB_WC, CHB_POSTE_TEL, CHB_COUCHAGE  FROM HOTEL.CHAMBRE;

DELETE PLANNING;

INSERT INTO PLANNING
SELECT CHB_ID, PLN_JOUR, CLI_ID, NB_PERS FROM HOTEL.PLANNING WHERE EXTRACT(YEAR FROM PLN_JOUR) = 2007;


INSERT INTO TRF_CHB
SELECT * FROM HOTEL.TRF_CHB WHERE EXTRACT(YEAR FROM TRF_DATE_DEBUT) = 2007;


CREATE TABLE TARIF AS 
    (SELECT * FROM HOTEL.TARIF WHERE EXTRACT (YEAR FROM TRF_DATE_DEBUT) = 2007);

ALTER TABLE TARIF ADD 
    CONSTRAINT PK_TRF_DATE_DEB PRIMARY KEY (TRF_DATE_DEBUT);
    
-- Exercice 3 : 
-- a) : Ecrire la requête permettant d'ajouter la contrainte suivante sur la table TELEPHONE 
-- L'attribut TEL_LOCALISATION ne peut prendre comme valeur que : "domicile", "portable" ou "bureau" et la valeur par défaut est "domicile"

-- Ajout contrainte check 
ALTER TABLE TELEPHONE ADD 
    CONSTRAINT CK_TEL_LOCAL CHECK (TEL_LOCALISATION IN ('domicile','portable','bureau'));
    
-- Ajout valeur par défaut
ALTER TABLE TELEPHONE MODIFY
    TEL_LOCALISATION DEFAULT 'domicile';

-- b) Tester en ajoutant la ligne suivante pour provoquer une erreur : 
INSERT INTO TELEPHONE
    VALUES(300,1,'GSM','07-12-58-96-00','INCONNU');
--  Pas possible car 'INCONNU' n'est pas dans liste de contrainte check

INSERT INTO TELEPHONE
    VALUES(300,1,'GSM','07-12-58-96-00',null);
--  Fonctionne car null est remplacé par valeur par défaut : 'domicile'

-- c) Tenter de supprimer le client nommé Alin Dupont. 
DELETE FROM CLIENT
    WHERE UPPER(CLI_NOM) = 'DUPONT' AND UPPER(CLI_PRENOM) = 'ALAIN';
-- Déclenche erreur car son numéro de tel est lié dans la table Télephone.

-- d) Faire les modifications nécessaires pour que lorsqu'un client est supprimé, ses téléphones soient automatiquement supprimés de la table TELEPHONE

ALTER TABLE TELEPHONE
    DROP CONSTRAINT FK_TEL_CLIENT;
    
ALTER TABLE TELEPHONE 
    ADD CONSTRAINT FK_TEL_CLIENT FOREIGN KEY (CLI_ID) REFERENCES CLIENT (CLI_ID) ON DELETE CASCADE;

ALTER TABLE ADRESSE
    DROP CONSTRAINT FK_ADRESSE_CLIENT;
    
ALTER TABLE ADRESSE 
    ADD CONSTRAINT FK_ADRESSE_CLIENT FOREIGN KEY (CLI_ID) REFERENCES CLIENT (CLI_ID) ON DELETE CASCADE;
    
ALTER TABLE PLANNING 
    DROP CONSTRAINT FK_PLANNING_CLIENT;
    
ALTER TABLE PLANNING 
    ADD CONSTRAINT FK_PLANNING_CLIENT FOREIGN KEY (CLI_ID) REFERENCES CLIENT (CLI_ID) ON DELETE CASCADE;
    
ALTER TABLE EMAIL
    DROP CONSTRAINT FK_CLI_ID_EMAIL;
    
ALTER TABLE EMAIL
    ADD CONSTRAINT FK_CLI_ID_EMAIL FOREIGN KEY (CLI_ID) REFERENCES CLIENT (CLI_ID) ON DELETE CASCADE;